baseURL = baseURL = "https://k3fair.github.io/simulation-workshop/"
languageCode = 'en-us'
title = 'My New Hugo Site'
t h e m e   =   ' a n a n k e ' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'
 
 