baseURL = "https://k3fair.github.io/simulation-workshop/"
languageCode = "en-gb"
title = "Kathyrn Fair"
theme = "ananke"

[author]
  name = "BDU<sup>2</sup> 2026"

[params]
  description = "Better Decisions Under Uncertainty"
  featured_image = "images/hero.png"
  cover_dimming_class = "bg-black-60"
  custom_css = ["css/custom.css"]

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true